// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bayesmatch_cpp
List bayesmatch_cpp(SEXP X0, SEXP boldX0, SEXP lambda0, SEXP treat0, SEXP total_gibbs0, SEXP thin0, SEXP param0, SEXP dv0, SEXP nu0, SEXP burnin0);
RcppExport SEXP SVMMatch_bayesmatch_cpp(SEXP X0SEXP, SEXP boldX0SEXP, SEXP lambda0SEXP, SEXP treat0SEXP, SEXP total_gibbs0SEXP, SEXP thin0SEXP, SEXP param0SEXP, SEXP dv0SEXP, SEXP nu0SEXP, SEXP burnin0SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type X0(X0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type boldX0(boldX0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type lambda0(lambda0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type treat0(treat0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type total_gibbs0(total_gibbs0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type thin0(thin0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type param0(param0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type dv0(dv0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type nu0(nu0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type burnin0(burnin0SEXP );
        List __result = bayesmatch_cpp(X0, boldX0, lambda0, treat0, total_gibbs0, thin0, param0, dv0, nu0, burnin0);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
